__all__ = ['clear',
           'dummy',
           'metashow',
           'rainbow',
           'rgbtest',
           'solidcolor',
           'spinthebottle',
           'strandtest',
           'theaterchase',
           'twocolorblend']
